from __future__ import annotations

import base64
import hashlib
import json
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import List

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

APP_DIR = Path.home() / ".local_password_manager"
CONFIG_FILE = APP_DIR / "config.json"
VAULT_FILE = APP_DIR / "vault.enc"
FACE_FILE = APP_DIR / "face_profile.enc"


def _utc_now() -> str:
    return datetime.utcnow().isoformat(timespec="seconds") + "Z"


def ensure_app_dir() -> None:
    APP_DIR.mkdir(parents=True, exist_ok=True)


def derive_fernet_key(master_password: str, user_salt: str) -> bytes:
    salt_bytes = hashlib.sha256(user_salt.encode("utf-8")).digest()
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt_bytes,
        iterations=390_000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(master_password.encode("utf-8")))
    return key


def hash_master(master_password: str, user_salt: str) -> str:
    data = f"{master_password}::{user_salt}".encode("utf-8")
    return hashlib.sha256(data).hexdigest()


@dataclass
class VaultEntry:
    profile: str
    name: str
    description: str
    password: str
    created_at: str
    updated_at: str


class VaultManager:
    def __init__(self, master_password: str, user_salt: str):
        ensure_app_dir()
        self.user_salt = user_salt
        self.fernet_key = derive_fernet_key(master_password, user_salt)
        self.fernet = Fernet(self.fernet_key)

    @staticmethod
    def app_initialized() -> bool:
        return CONFIG_FILE.exists()

    @staticmethod
    def init_master(master_password: str, user_salt: str) -> None:
        ensure_app_dir()
        key = derive_fernet_key(master_password, user_salt)
        fernet = Fernet(key)
        token = fernet.encrypt(b"vault-ok").decode("utf-8")
        config = {
            "user_salt": user_salt,
            "master_hash": hash_master(master_password, user_salt),
            "token": token,
            "created_at": _utc_now(),
        }
        CONFIG_FILE.write_text(json.dumps(config, indent=2), encoding="utf-8")
        if not VAULT_FILE.exists():
            fernet_vault = fernet.encrypt(b"[]")
            VAULT_FILE.write_bytes(fernet_vault)

    @staticmethod
    def load_config() -> dict:
        if not CONFIG_FILE.exists():
            raise FileNotFoundError("Master account is not initialized.")
        return json.loads(CONFIG_FILE.read_text(encoding="utf-8"))

    @staticmethod
    def validate_master(master_password: str) -> tuple[bool, str]:
        config = VaultManager.load_config()
        user_salt = config["user_salt"]
        if hash_master(master_password, user_salt) != config["master_hash"]:
            return False, ""
        key = derive_fernet_key(master_password, user_salt)
        fernet = Fernet(key)
        try:
            msg = fernet.decrypt(config["token"].encode("utf-8"))
            return msg == b"vault-ok", user_salt
        except Exception:
            return False, ""

    def read_entries(self) -> List[VaultEntry]:
        if not VAULT_FILE.exists():
            return []
        try:
            payload = self.fernet.decrypt(VAULT_FILE.read_bytes()).decode("utf-8")
            raw = json.loads(payload)
            return [VaultEntry(**entry) for entry in raw]
        except Exception:
            return []

    def write_entries(self, entries: List[VaultEntry]) -> None:
        data = [asdict(entry) for entry in entries]
        encrypted = self.fernet.encrypt(json.dumps(data, indent=2).encode("utf-8"))
        VAULT_FILE.write_bytes(encrypted)

    def upsert_entry(self, profile: str, name: str, description: str, password: str) -> None:
        entries = self.read_entries()
        now = _utc_now()
        for entry in entries:
            if entry.profile == profile and entry.name == name:
                entry.description = description
                entry.password = password
                entry.updated_at = now
                self.write_entries(entries)
                return
        entries.append(
            VaultEntry(
                profile=profile,
                name=name,
                description=description,
                password=password,
                created_at=now,
                updated_at=now,
            )
        )
        self.write_entries(entries)

    def export_env(self, output_file: str) -> None:
        lines = [
            "# Generated by Local Password Manager",
            f"DECRYPTION_KEY={self.fernet_key.decode('utf-8')}",
            f"VAULT_FILE={VAULT_FILE}",
            f"EXPORTED_AT={_utc_now()}",
        ]
        Path(output_file).write_text("\n".join(lines) + "\n", encoding="utf-8")

    def save_face_profile(self, encoded_blob: bytes) -> None:
        FACE_FILE.write_bytes(self.fernet.encrypt(encoded_blob))

    def load_face_profile(self) -> bytes | None:
        if not FACE_FILE.exists():
            return None
        try:
            return self.fernet.decrypt(FACE_FILE.read_bytes())
        except Exception:
            return None
